### ISSUE TITLE
Armor bar locked y-axis.

### ISSUE THREAD

**Issue by Marotheit** [IzzyDotExe/ArmorSkin#1]
The armor bar is locked on the y-axis and is unable to be edited. This conflicts with mods like [Raised](https://modrinth.com/mod/raised).

Integration with Raised (and similar mods) would be nice, but a configuration option to be able to raise the armor bar would probably be much simpler.

See example below for conflict.

![Screenshot](https://github.com/IzzyDotExe/ArmorSkin/assets/26125775/41c8860c-6732-40c5-862f-ffc3e0cacef7).

**Comment by IzzyDotExe** [comment]
Hi, 

the reason it does this is because i'm essentially replacing the entire part of the hud rendering method that renders the armor instead of mixing where necessary to change the UV values. 

I do plan on fixing this for compat with my other mod removehud which should in turn fix compat with raised aswell. 

Ill keep this issue open until that is fixed but it's on the way for v0.2. Thanks for using my mod!

**Comment by IzzyDotExe** [comment]
It's been fixed! New version will be available on curse and modrinth soon. In the meantime you can fetch it on the GitHub releases.

![image](https://github.com/IzzyDotExe/ArmorSkin/assets/44146685/224475ec-2722-4e92-ad95-7472ea50bcc2)
